# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/justin/Downloads/clion-2017.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/justin/Downloads/clion-2017.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/justin/CLionProjects/AutoSCP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/justin/CLionProjects/AutoSCP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/justin/Downloads/clion-2017.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/justin/Downloads/clion-2017.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/justin/CLionProjects/AutoSCP/CMakeFiles /home/justin/CLionProjects/AutoSCP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/justin/CLionProjects/AutoSCP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AutoSCP

# Build rule for target.
AutoSCP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AutoSCP
.PHONY : AutoSCP

# fast build rule for target.
AutoSCP/fast:
	$(MAKE) -f CMakeFiles/AutoSCP.dir/build.make CMakeFiles/AutoSCP.dir/build
.PHONY : AutoSCP/fast

#=============================================================================
# Target rules for targets named src

# Build rule for target.
src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src
.PHONY : src

# fast build rule for target.
src/fast:
	$(MAKE) -f src/CMakeFiles/src.dir/build.make src/CMakeFiles/src.dir/build
.PHONY : src/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/AutoSCP.dir/build.make CMakeFiles/AutoSCP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/AutoSCP.dir/build.make CMakeFiles/AutoSCP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/AutoSCP.dir/build.make CMakeFiles/AutoSCP.dir/main.cpp.s
.PHONY : main.cpp.s

src/fileutils.o: src/fileutils.cpp.o

.PHONY : src/fileutils.o

# target to build an object file
src/fileutils.cpp.o:
	$(MAKE) -f CMakeFiles/AutoSCP.dir/build.make CMakeFiles/AutoSCP.dir/src/fileutils.cpp.o
.PHONY : src/fileutils.cpp.o

src/fileutils.i: src/fileutils.cpp.i

.PHONY : src/fileutils.i

# target to preprocess a source file
src/fileutils.cpp.i:
	$(MAKE) -f CMakeFiles/AutoSCP.dir/build.make CMakeFiles/AutoSCP.dir/src/fileutils.cpp.i
.PHONY : src/fileutils.cpp.i

src/fileutils.s: src/fileutils.cpp.s

.PHONY : src/fileutils.s

# target to generate assembly for a file
src/fileutils.cpp.s:
	$(MAKE) -f CMakeFiles/AutoSCP.dir/build.make CMakeFiles/AutoSCP.dir/src/fileutils.cpp.s
.PHONY : src/fileutils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AutoSCP"
	@echo "... src"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/fileutils.o"
	@echo "... src/fileutils.i"
	@echo "... src/fileutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

